resources:
  requests:
    memory: "256Mi"
    cpu: "50m"
  limits:
    memory: "512Mi"
    cpu: "100m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

livenessProbe:
  httpGet:
    path: /
    port: 16686
  initialDelaySeconds: 10
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: 16686
  initialDelaySeconds: 10
  periodSeconds: 5

restartPolicy: Always

provisionDataStore:
  cassandra: false
  kafka: true
