resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

livenessProbe:
  exec:
    command:
      - sh
      - -c
      - "pg_isready -U postgres"
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - "pg_isready -U postgres"
  initialDelaySeconds: 10
  periodSeconds: 10

restartPolicy: Always
