replicaCount: 1

image:
  repository: graylog/graylog
  tag: "4.2"
  pullPolicy: IfNotPresent

opensearch:
  enabled: true
  version: "2.4.0" # Ensure compatibility with Graylog
  security:
    enabled: true
    # Adds security plugin and ensures it is properly configured
    config:
      plugins.security.disabled: false
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    storageClass: standard # Adjust to your Kubernetes setup
  securityContext:
    runAsUser: 1000
    fsGroup: 1000

mongodb:
  enabled: true
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

graylog:
  web:
    service:
      enabled: true
      type: ClusterIP
      port: 9000

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

probes:
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
    path: /api/system/liveness
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
    path: /api/system/health
  startupProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 10
    path: /api/system/health

restartPolicy:
  enabled: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

persistence:
  enabled: true
  size: 10Gi
  storageClass: standard # Adjust to your Kubernetes setup
